name: BirdWeather analysis (last 4 weeks)

on:
  workflow_dispatch:   # only runs when you manually trigger it

permissions:
  contents: write

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system libraries for curl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("readr","dplyr","lubridate","ggplot2", "suncalc"), repos = "https://cloud.r-project.org")'

      - name: Run 4-weeks analysis script
        run: |
          Rscript scripts/analyse_last4weeks.R

      - name: Commit and push analysis outputs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output || echo "Nothing to add"
          git commit -m "Update analysis (last 4 weeks)" || echo "Nothing to commit"
          git push
